version: '3'

services:
  stepper-control:
    build: .
    privileged: true  # Needed for I2C access
    devices:
      - "/dev/i2c-1:/dev/i2c-1"  # I2C bus
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Serial port
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 forwarding
    network_mode: "host"  # Needed for display